// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBERCrNyI4j4-km0UgGxNNS5sDtA9gdgm8',
    appId: '1:278096529200:web:b7381ba4cf44f215a32af5',
    messagingSenderId: '278096529200',
    projectId: 'my-todo-list-127d3',
    authDomain: 'my-todo-list-127d3.firebaseapp.com',
    databaseURL: 'https://my-todo-list-127d3-default-rtdb.firebaseio.com',
    storageBucket: 'my-todo-list-127d3.firebasestorage.app',
    measurementId: 'G-HQ1H1E1P5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8_Z4qvqpbsQ4gigrejRVb99c_GNGunPc',
    appId: '1:278096529200:android:ccc1e3c1e17ed1daa32af5',
    messagingSenderId: '278096529200',
    projectId: 'my-todo-list-127d3',
    databaseURL: 'https://my-todo-list-127d3-default-rtdb.firebaseio.com',
    storageBucket: 'my-todo-list-127d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnwoodzfaMqPYj0fPLqKBb7IM1FUc-VXg',
    appId: '1:278096529200:ios:633e06a6bb8624f8a32af5',
    messagingSenderId: '278096529200',
    projectId: 'my-todo-list-127d3',
    databaseURL: 'https://my-todo-list-127d3-default-rtdb.firebaseio.com',
    storageBucket: 'my-todo-list-127d3.firebasestorage.app',
    iosBundleId: 'com.example.thirdTaskTodoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnwoodzfaMqPYj0fPLqKBb7IM1FUc-VXg',
    appId: '1:278096529200:ios:633e06a6bb8624f8a32af5',
    messagingSenderId: '278096529200',
    projectId: 'my-todo-list-127d3',
    databaseURL: 'https://my-todo-list-127d3-default-rtdb.firebaseio.com',
    storageBucket: 'my-todo-list-127d3.firebasestorage.app',
    iosBundleId: 'com.example.thirdTaskTodoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBERCrNyI4j4-km0UgGxNNS5sDtA9gdgm8',
    appId: '1:278096529200:web:3c42ec18d7e7f6f6a32af5',
    messagingSenderId: '278096529200',
    projectId: 'my-todo-list-127d3',
    authDomain: 'my-todo-list-127d3.firebaseapp.com',
    databaseURL: 'https://my-todo-list-127d3-default-rtdb.firebaseio.com',
    storageBucket: 'my-todo-list-127d3.firebasestorage.app',
    measurementId: 'G-F0JMV5FDXF',
  );
}
